// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to generate tech-related questions and answers for a memory game.
 *
 * - generateTechContent - A function that generates tech content.
 * - GenerateTechContentInput - The input type for the generateTechContent function.
 * - GenerateTechContentOutput - The return type for the generateTechContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTechContentInputSchema = z.object({
  numPairs: z
    .number()
    .describe('The number of question and answer pairs to generate.')
    .default(8),
});
export type GenerateTechContentInput = z.infer<typeof GenerateTechContentInputSchema>;

const TechContentPairSchema = z.object({
  question: z.string().describe('A tech-related question, such as a DSA question or coding question.'),
  answer: z.string().describe('The answer to the tech-related question.'),
});

const GenerateTechContentOutputSchema = z.object({
  pairs: z.array(TechContentPairSchema).describe('An array of question and answer pairs.'),
});
export type GenerateTechContentOutput = z.infer<typeof GenerateTechContentOutputSchema>;

export async function generateTechContent(input: GenerateTechContentInput): Promise<GenerateTechContentOutput> {
  return generateTechContentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTechContentPrompt',
  input: {schema: GenerateTechContentInputSchema},
  output: {schema: GenerateTechContentOutputSchema},
  prompt: `You are generating content for a tech-themed memory game.  Generate {{numPairs}} pairs of questions and answers related to computer science, data structures and algorithms, and general technical knowledge.  The questions should be challenging but not obscure.  The answers should be concise and accurate.

Output should be a JSON array of question and answer pairs.  Each pair should have a "question" field and an "answer" field.

For example:

[
  {
    "question": "What is the time complexity of binary search?",
    "answer": "O(log n)",
  },
  {
    "question": "What does DSA stand for?",
    "answer": "Data Structures and Algorithms",
  }
]
`,
});

const generateTechContentFlow = ai.defineFlow(
  {
    name: 'generateTechContentFlow',
    inputSchema: GenerateTechContentInputSchema,
    outputSchema: GenerateTechContentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
